//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
#![allow(unused_imports)]
pub use super::category::Entity as Category;
pub use super::collection::Entity as Collection;
pub use super::feedback::Entity as Feedback;
pub use super::photo_album::Entity as PhotoAlbum;
